pipeline{
    agent {
        kubernetes {
            yaml """
apiVersion: v1
kind: Pod
metadata:
  labels:
    jenkins: agent
spec:
  containers:
  - name: docker
    image: docker:20.10-cli
    command:
    - cat
    tty: true
    volumeMounts:
    - name: docker-sock
      mountPath: /var/run/docker.sock
  volumes:
  - name: docker-sock
    hostPath:
      path: /var/run/docker.sock
"""
            defaultContainer 'docker'
        }
    }
    parameters{
        string(name: 'ENV', defaultValue: 'dev')
    }
    environment{
        DOCKER_HUB = "iammaheshn"
        IMAGE_NAME = "applicationend"
        IMAGE_TAG = "${params.ENV}-${env.BUILD_ID}"
    }
    stages{
        stage("code checkout"){
            steps{
                script{
                    git credentialsId: 'github_credentials', url: 'https://github.com/realmemahesh/Jenkins.git'
                }
            }
        }
        stage("Docker build"){
            steps{
                script{
                    sh "pwd"
                    sh "ls -l"
                    sh "docker --version"
                    sh "docker build -t ${DOCKER_HUB}/${IMAGE_NAME}:${IMAGE_TAG} 3-tier-application/applicationend/."
                }
            }
        }
        stage("Docker push"){
            steps{
                script{
                    withCredentials([usernamePassword(credentialsId: 'dockerhub_credentials', passwordVariable: 'DOCKER_PASSWORD', usernameVariable: 'DOCKER_USERNAME')]) {
                        sh "echo ${DOCKER_PASSWORD} | docker login -u ${DOCKER_USERNAME} --password-stdin"
                        sh "docker push ${DOCKER_HUB}/${IMAGE_NAME}:latest"
                    }
                }
            }
        }
    }
    post{
        success {
            echo "Build and deployment successful"
        }
        failure {
            echo "Build failed"
        }
    }
}